definitions:
  services:
    docker:
      memory: 4098

pipelines:
  branches:
    development:
      - step:
          name: Build and Push Docker Image
          image: atlassian/pipelines-awscli
          size: 2x
          caches:
            - docker
          services:
            - docker
          script:
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - export DOCKER_URI=$DOCKER_IMAGE_URL:development
            # Login to docker registry on AWS
            - eval $(aws ecr get-login --no-include-email)
            # Build image
            - docker build --build-arg NODE_ENV=development -t $DOCKER_URI .
            # Push image to private registry
            - docker push $DOCKER_URI
      - step:
         name: Deploy to ECS
         image: atlassian/pipelines-awscli
         size: 2x
         script:
           - pipe: atlassian/aws-ecs-deploy:1.1.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
               CLUSTER_NAME: $CLUSTER_DEV
               SERVICE_NAME: $SERVICE_DEV
               TASK_DEFINITION: "dev-task-definition.json"
    master:
      - step:
          name: Build and Push Docker Image
          image: atlassian/pipelines-awscli
          size: 2x
          caches:
            - docker
          services:
            - docker
          script:
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - export DOCKER_URI=$DOCKER_IMAGE_URL:latest
            # Login to docker registry on AWS
            - eval $(aws ecr get-login --no-include-email)
            # Build image
            - docker build --build-arg NODE_ENV=production -t $DOCKER_URI .
            # Push image to private registry
            - docker push $DOCKER_URI
      - step:
         name: Deploy to ECS
         image: atlassian/pipelines-awscli
         size: 2x
         script:
           - pipe: atlassian/aws-ecs-deploy:1.1.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
               CLUSTER_NAME: $CLUSTER
               SERVICE_NAME: $SERVICE
               TASK_DEFINITION: "task-definition.json"
